version: '3.3'
services:
  app:
    container_name: employee-jooq
    image: employee-jooq
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=employee